# Set up the Rust toolchain.
language: rust
rust:
  - stable
  - beta
  - nightly

os:
- linux
- osx
- windows

branches:
  only:
    - staging
    - trying
    - master
    - /release-.*/

# Allow for occasional compiler breakage on nightly Rust.
matrix:
  allow_failures:
    - rust: nightly
    - rust: beta
  fast_finish: true

script:
  - cargo test --verbose --all --all-features
