# Set up the Rust toolchain.
language: rust
rust:
  - stable
  - beta
  - nightly

before_script:
  - rustup component add clippy-preview
  - export PATH=$PATH:/home/travis/.cargo/bin
  - export RUSTFLAGS="-D warnings"

os:
- linux
- osx
- windows

branches:
  only:
    - staging
    - trying
    - master
    - /release-.*/

# Allow for occasional compiler breakage on nightly Rust.
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - rust: stable
      script:
        - cargo test --all --all-features --locked
        - rustup component add rustfmt-preview
        - cargo fmt -- --write-mode=diff

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

script:
  - cargo clippy --all --all-features -- -D warnings
  - cargo test --verbose --all --all-features

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  make install DESTDIR=../../kcov-build &&
  cd ../.. &&
  rm -rf kcov-master &&
  for file in target/debug/laminar-*[^\.d]; do mkdir -p "target/cov/$(basename $file)"; ./kcov-build/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"

